# Remova ou comente estas linhas:
org.gradle.java.home=C\:\\Program Files\\Android\\Android Studio\\jbr
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false
# Remova ou comente estas linhas:
org.gradle.java.home=C\:\\Program Files\\Android\\Android Studio\\jbr
org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.auto-download=false